### ISSUE TITLE
 release trigger: tag added one commit behind

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ops-repo-automation#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior:

The release **TAG** should be on the commit that contains the release version number in the codebase.

### Current Behavior:

Any release going through CI/CD sets the release **TAG** on the commit _before_ the merged version package - so it's at the wrong commit.

![image](https://github.com/user-attachments/assets/86551d62-4a4f-4ece-866d-81fc3417c6ec)

More details: [see discord discussion](https://discord.com/channels/517362899170230292/1136202513402581006/1293243813380358185) :)

### Steps To Reproduce:

1. Trigger release action.

OR:

1. Find Kuba.
2. Ask Kuba.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

Side note - these current releases have now been 'manually' fixed.

The code defining the tag name is here:

https://github.com/ynput/ops-repo-automation/blob/develop/.github/workflows/release_trigger.yml#L187-L198

**Comment by philnewm** [comment]
Thanks for flagging this :+1: 

I'll add it to the lest of tests I'll need to implement for this stuff.
Right now I only got about an hour but I'll see what I can do.

**Comment by philnewm** [comment]
There are only three palces in `.github/workflows/release_trigger.yml` which can potentially write git tags

job: merge-to-main, last step
```yaml
      - name: 🔏 Push to protected ${{ vars.MAIN_BRANCH }} branch
        uses: CasperWA/push-protected@v2.16.0
        with:
          token: ${{ env.GH_TOKEN }}
          branch: ${{ vars.MAIN_BRANCH }}
          tags: false
          unprotect_reviews: false
```

job: update-develop, second last step

```yaml
      - name: 🔏 Push to protected ${{ github.ref_name }} branch
        uses: CasperWA/push-protected@v2.16.0
        with:
          token: ${{ env.GH_TOKEN }}
          branch: ${{ github.ref_name }}
          tags: false
          unprotect_reviews: false
```

job: create-release, last step where it's supposed to happen

```yaml
      - name: 🚀 Create Github Release Draft
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ env.NEXT_VERSION }}"
          generateReleaseNotes: true
          artifacts: |
            ${{ needs.build-from-main.outputs.artifact_file }}
          token: ${{ env.GH_TOKEN }}
          draft: ${{ env.DRAFT }}
```

I did notice, that in job build-from-main the tags option for the "push-protected" was set to true.
And according to the log output of push-protected in a workflow run this might be the issue

```code
Switched to branch 'main'
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)
HEAD is now at 1082e2e [Automated] Add generated package files from main
remote: Bypassed rule violations for refs/heads/main:        
remote: 
remote: - Cannot update this protected ref.        
remote: 
To https://github.com/ynput/ayon-maya.git
   14a757b..1082e2e  main -> main

Pushing tags ...
Everything up-to-date
Pushing tags ... DONE!
```

Currently testing if switching that option to false fixes it.

@iLLiCiTiT was that issue present from the beginning on or did it happen after soem changes I implemented?
